# Generated by Django 4.1.4 on 2022-12-18 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'Usd'), ('SOUM', 'Soum')], default='SOUMS', max_length=255, null=True)),
                ('main_language', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('phone', models.CharField(max_length=255)),
                ('wifi_password', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('information', models.TextField(blank=True, null=True)),
                ('work_hours_from', models.TextField(blank=True, null=True)),
                ('work_hours_to', models.TextField(blank=True, null=True)),
                ('theme', models.TextField(blank=True, choices=[('orange', 'orange'), ('sky', 'sky'), ('fuchsia', 'fuchsia'), ('blue', 'blue'), ('dark', 'dark'), ('teal', 'teal'), ('rose', 'rose'), ('indigo', 'indigo'), ('blcyanue', 'cyan'), ('slate', 'slate')], default='orange', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
